runtime: python39
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  WEBHOOK_KEY: ""

includes:
- secret.yaml

handlers:
- url: /assets
  static_dir: assets

- url: /.*
  script: auto
  secure: always

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10